[package]
name = "betree_storage_stack"
version = "0.1.0"
authors = ["Felix Wiedemann <felix@kann.it>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[[bench]]
name = "cache"
harness = false

[[bench]]
name = "allocator"
harness = false

[dependencies]
futures = { version = "0.3", features = ["thread-pool"] }
serde = { version = "1.0", features = [ "derive" ] }
bincode = "1.0"
error-chain = "0.12"
libc = "0.2"
parking_lot = "0.11"
lock_api = { version = "0.4", features = ["owning_ref"] }
owning_ref = "0.4"
log = { version = "0.4", features = [ "release_max_level_info" ] }
byteorder = "1.0"
lz4 = "1.21"
seqlock = { path = "seqlock/" }
twox-hash = "1.6"
stable_deref_trait = "1.1"
unbytify = "0.2"
toml = "0.5"
itertools = "0.9"
ref_slice = "1.1"
env_logger = "0.8"
scoped_threadpool = "0.1"
indicatif = "0.15"
async-trait = "0.1"
jemallocator = { version = "0.3", features = [ "background_threads" ] }

zstd = { version = "0.5", default-features = false }
zstd-safe = { version = "2.0", default-features = false }


[dev-dependencies]
rand = "0.7"
rand_xorshift = "0.2"
quickcheck = "0.9"
quickcheck_macros = "0.9"
clap = "2.33"
bencher = "0.1"

criterion = "0.3"
